{
	"version": 1770668492,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/spr_alma-sheet0.png",
		"images/spr_personagem-sheet0.png",
		"images/spr_personagem-sheet1.png",
		"images/spr_personagem-sheet2.png",
		"images/fundo.png",
		"images/tilemap.png",
		"images/pisoterra-sheet0.png",
		"images/plataformaterra-sheet0.png",
		"images/planta-sheet0.png",
		"images/planta2-sheet0.png",
		"images/cantonevedireito-sheet0.png",
		"images/cantoneveesq-sheet0.png",
		"images/cantoterradireito-sheet0.png",
		"images/cantoterraesq-sheet0.png",
		"images/arvoreg-sheet0.png",
		"images/arvorep-sheet0.png",
		"images/písoneve-sheet0.png",
		"images/pedramarromg-sheet0.png",
		"images/pedracinzag-sheet0.png",
		"images/pedramarromp-sheet0.png",
		"images/pedracinzap-sheet0.png",
		"images/matog-sheet0.png",
		"images/matop-sheet0.png",
		"images/arvore-sheet0.png",
		"images/neve-sheet0.png",
		"images/chaobaixo-sheet0.png",
		"images/chaoalto-sheet0.png",
		"images/pisoflutuante-sheet0.png",
		"images/vilao-sheet0.png",
		"images/andando-sheet0.png",
		"images/andando-sheet1.png",
		"images/baumensagem-sheet0.png",
		"images/chavemensagem-sheet0.png",
		"images/temperaturaartico-sheet0.png",
		"images/lixonoartico-sheet0.png",
		"images/pngtreepckeyboardarrowkeysblackvectoriconconceptsetsignvectorpngimage_-sheet0.png",
		"images/fogueira-sheet0.png",
		"images/fogueira-sheet1.png",
		"images/icestone-sheet0.png",
		"images/chest-sheet0.png",
		"images/rustycrate-sheet0.png",
		"images/chave-sheet0.png",
		"images/lixo-sheet0.png",
		"images/parabens-sheet0.png",
		"images/gameover-sheet0.png",
		"images/creditos-sheet0.png",
		"images/capaaventurapolar-sheet0.png",
		"images/btcreditos-sheet0.png",
		"images/btjogar-sheet0.png",
		"images/btmenu-sheet0.png",
		"images/btvoltar-sheet0.png",
		"images/vilao2-sheet0.png",
		"images/vilao2-sheet1.png",
		"images/vilao2-sheet2.png",
		"images/1vida-sheet0.png",
		"images/1vida-sheet1.png",
		"images/sprite-sheet0.png",
		"images/coleta-sheet0.png",
		"images/fundo2-sheet0.png",
		"images/agua-sheet0.png",
		"images/wasd-sheet0.png",
		"images/analogico-sheet0.png",
		"images/gamepad-sheet0.png",
		"images/chavepreta-sheet0.png",
		"images/chavepreta-sheet1.png",
		"images/icestonepreta-sheet0.png",
		"images/icestonepreta-sheet1.png",
		"images/termometropreto-sheet0.png",
		"images/termometropreto-sheet1.png",
		"images/lixopreto-sheet0.png",
		"images/lixopreto-sheet1.png",
		"images/parede-sheet0.png",
		"images/gelonaagua-sheet0.png",
		"images/pisoneve-sheet0.png",
		"images/ponte-sheet0.png",
		"images/iglu-sheet0.png",
		"images/tilemap2.png",
		"images/bau-sheet0.png",
		"images/escada-sheet0.png",
		"images/sensoresq-sheet0.png",
		"images/sensordireita-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/som-sheet0.png",
		"images/sommutado-sheet0.png",
		"images/termometro-sheet0.png",
		"images/jump-sheet0.png",
		"images/c396c0f63eac4741affd2810e31f-sheet0.png",
		"images/btcontinuar-sheet0.png",
		"images/c396c0f63eac4741affd2810e31f2-sheet0.png",
		"media/andando na pedra.m4a",
		"media/andando na pedra.ogg",
		"media/andando no gelo.m4a",
		"media/andando no gelo.ogg",
		"media/bau abrindo.m4a",
		"media/bau abrindo.ogg",
		"media/boss morendo.m4a",
		"media/boss morendo.ogg",
		"media/caindo na agua.m4a",
		"media/caindo na agua.ogg",
		"media/capa musica.m4a",
		"media/capa musica.ogg",
		"media/coletando item.m4a",
		"media/coletando item.ogg",
		"media/dano.m4a",
		"media/dano.ogg",
		"media/fogueira.m4a",
		"media/fogueira.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/musica de fundo.m4a",
		"media/musica de fundo.ogg",
		"media/passo na neve.m4a",
		"media/passo na neve.ogg",
		"media/pulo.m4a",
		"media/pulo.ogg",
		"media/vitoria.m4a",
		"media/vitoria.ogg",
		"media/passo-na-neve_re7xvnip.m4a",
		"media/passo-na-neve_re7xvnip.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}